Apps/Apps.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apps.BLL;
using Apps.IBLL;
using Apps.Models;
using Apps.Models.Sys;
using Microsoft.Practices.Unity;

namespace Apps.Web.Controllers
{
    public class HomeController : Controller
    {
        [Dependency]
        public IHomeBLL homeBLL { get; set; }
        public ActionResult Index()
        {
            AccountModel account = new AccountModel();
            account.Id = "admin";
            account.TrueName = "admin";
            Session["Account"] = account;
            return View();
        }

        [HttpPost]
        public JsonResult GetTree(string id)
        {
            var menus = homeBLL.GetMenuByPersonId(id);
            var jsonData = (from m in menus
                            select new
                            {
                                id = m.ID,
                                text = m.Name,
                                value = m.Url,
                                showcheck = false,
                                complete = false,
                                isexpand = false,
                                checkstate = 0,
                                hasChildren = (bool)m.IsLast ? false : true,
                                Icon = m.Iconic
                            });
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
    }
}

Apps/Apps.Web/Controllers/SysLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apps.Common;
using Apps.Models;
using Microsoft.Practices.Unity;
using Apps.IBLL;
using Apps.Models.Sys;
using Apps.Core;
using Apps.Admin;

namespace Apps.Web.Controllers
{
    public class SysLogController : BaseController
    {

        [Dependency]
        public ISysLogBLL SysLogBLL { get; set; }

        ValidationErrors errors = new ValidationErrors();

        // GET: SysLog
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetList(GridPager pager, string queryStr)
        {
            List<SysLog> list = SysLogBLL.GetList(ref pager, queryStr);
            var json = new
            {
                total = pager.totalRows,
                rows = (from r in list
                        select new SysLogModel()
                        {
                            ID = r.ID,
                            Operator = r.Operator,
                            Message = r.Message,
                            Result = r.Result,
                            Type = r.Type,
                            Module = r.Module,
                            CreateTime = r.CreateTime

                        }).ToArray()

            };

            return Json(json);
        }


        #region 详细   
        public ActionResult Details(string id)
        {

            SysLog entity = SysLogBLL.GetById(id);
            SysLogModel info = new SysLogModel()
            {
                ID = entity.ID,
                Operator = entity.Operator,
                Message = entity.Message,
                Result = entity.Result,
                Type = entity.Type,
                Module = entity.Module,
                CreateTime = entity.CreateTime,
            };
            return View(info);
        }

        #endregion

        [HttpPost]
        public JsonResult Delete(string id)
        {
            if (SysLogBLL.Delete(ref errors, id))
            {
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + id.ToString(), Result = "成功", Type = "删除", Module = "系统日志" });
                return Json(JsonHandler.CreateMessage(1, "删除成功"), JsonRequestBehavior.AllowGet);
            }
            else
            {
                string ErrorCol = errors.Error;
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + id.ToString(), Result = "失败", Type = "删除", Module = "系统日志" });
                return Json(JsonHandler.CreateMessage(0, "删除失败" + ErrorCol), JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Apps/Apps.Web/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/easyuicss")
    @Styles.Render("~/Content/tree")
</head>
<body>
    <div class="easyui-layout" data-options="fit:'true'">
        @* Head 网页头 *@
        <div data-options="region:'north',split:true,collapsible:false" style="height:100px;">
            <div style="line-height:93px;display: inline-block;padding: 0 5px;width: 100px;text-align: center;">
                Logo
            </div>
            <div style="display:inline-block">
                Demo 管理系统
            </div>
        </div>
        @* West 左侧树形*@
        <div data-options="region:'west',title:'菜单列表',split:true" style="width:180px;">
            <div id="RightTree" style="padding-top:5px;"></div>
        </div>
        @* Center 主体内容*@
        <div data-options="region:'center',border:false">
            <div id="mainTab" class="easyui-tabs" data-options="fit:'true'">
                <div title="系统异常" data-options="closable:true" style="overflow:hidden">
                    <iframe scrolling="auto" frameborder="0" src="@Url.Action("Index","SYSException")" style="width:100%;height:100%">
                        ...
                    </iframe>
                </div>
                <div title="系统日志" data-options="closable:true" style="overflow:hidden">
                    <iframe scrolling="auto" frameborder="0" src="@Url.Action("Index","SysLog")" style="width:100%;height:100%">
                        ...
                    </iframe>
                </div>
            </div>
        </div>
        @* 右键菜单  *@
        <div id="tab_menu" class="easyui-menu" style="width:150px;">
            <div id="tab_menu-tabrefresh" data-options="iconCls:'icon-reload'">刷新</div>
            <div id="tab_menu-openFrame">在新的窗体打开</div>
            <div id="tab_menu-tabcloseall">关闭所有</div>
            <div id="tab_menu-tabcloseothers">关闭其他标签页</div>
            <div class="menu-sep"></div>
            <div id="tab_menu-tabcloseleft">关闭左边</div>
            <div id="tab_menu-tabcloseright">关闭右边</div>
            <div id="tab_menu-tabclose" data-options="iconCls:'icon-remove'">关闭</div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/easyui")
    @Scripts.Render("~/bundles/jquerytree")
    @Scripts.Render("~/bundles/home")

</body>
</html>