Apps/Apps.Web/Controllers/SysSampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Apps.BLL;
using Apps.IBLL;
using Apps.Models;
using Microsoft.Practices.Unity;
using Apps.Models.Sys;
using Apps.Common;
using Apps.Admin;

namespace Apps.Web.Controllers
{
    public class SysSampleController : BaseController
    {
        //private ISysSampleBLL bll = new SysSampleBLL();
        /// <summary>
        /// 业务层注入
        /// </summary>
        [Dependency]
        public ISysSampleBLL m_BLL { get; set; }

        ValidationErrors errors = new ValidationErrors();
        // GET: SysSample
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetList(GridPager pager)
        {
            var list = m_BLL.GetList(ref pager);

            var json = new
            {
                total = pager.totalRows,
                rows = (from r in list
                        select new SysSampleModel
                        {
                            ID = (int)r.ID,
                            Name = r.Name,
                            Bir = r.Bir,
                            Age = r.Age,
                            CreateTime = r.CreateTime,
                            Note = r.Note,
                            Photo = r.Photo
                        })
            };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        #region Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(true)]
        public ActionResult Create(SysSampleModel model)
        {
            if (m_BLL.Create(ref errors, model))
            {
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + model.ID.ToString() + ",Name:" + model.Name, Result = "成功", Type = "创建", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(1, "插入成功"), JsonRequestBehavior.AllowGet);
            }
            else
            {
                string ErrorCol = errors.Error;
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + model.ID.ToString() + ",Name:" + model.Name, Result = "失败", Type = "创建", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(0, "插入失败" + ErrorCol), JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        public ActionResult Details(int id)
        {
            var entity = m_BLL.GetById(id);
            return View(entity);
        }

        #region Edit
        public ActionResult Edit(int id)
        {
            var entity = m_BLL.GetById(id);

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SysSampleModel model)
        {
            if (m_BLL.Edit(ref errors, model))
            {
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + model.ID.ToString() + ",Name:" + model.Name, Result = "成功", Type = "修改", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(1, "修改成功"), JsonRequestBehavior.AllowGet);
            }
            else
            {
                string ErrorCol = errors.Error;
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + model.ID.ToString() + ",Name:" + model.Name, Result = "失败", Type = "修改", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(0, "修改失败" + ErrorCol), JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Delete
        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (m_BLL.Delete(ref errors, id))
            {
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + id.ToString(), Result = "成功", Type = "删除", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(1, "删除成功"), JsonRequestBehavior.AllowGet);
            }
            else
            {
                string ErrorCol = errors.Error;
                LogHandler.WriteServiceLog(new SysLog { Operator = "虚拟用户", Message = "ID:" + id.ToString(), Result = "失败", Type = "删除", Module = "样例程序" });
                return Json(JsonHandler.CreateMessage(0, "删除失败" + ErrorCol), JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

    }
}

Apps/Apps.Web/Views/SysSample/Create.cshtml
@model Apps.Models.Sys.SysSampleModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@section style{
    <style>
        .mvctool {
            background: #d2e0f2;
        }

            .mvctool::after {
                clear: both;
                content: '';
                display: block;
            }

        .formEditTable {
            width: 700px;
        }

            .formEditTable tr {
                border-bottom: 1px dashed;
            }

                .formEditTable tr td input {
                    margin: 2px;
                    width: 100%;
                }
    </style>
}
<div class="mvctool bgb">
    <a id="btnSave" style="float:left" class="l-btn l-btn-plain">
        <span class="l-btn-left">
            <span class="l-btn-text icon-save" style="padding-left:20px;">保存</span>
        </span>
    </a>
</div>

@using (Html.BeginForm("Create", "SysSample", FormMethod.Post, new { Id = "CreateForm" }))
{
    @Html.AntiForgeryToken()

    <table class="formEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Name) :
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Name)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Age) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Age)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Age)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Bir) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Bir)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Bir)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Note):
                </td>
                <td>
                    @Html.EditorFor(model => model.Note)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Note)
                </td>
            </tr>

            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.CreateTime):
                </td>
                <td>
                    @Html.EditorFor(model => model.CreateTime)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.CreateTime)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Photo) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Photo)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Photo)
                </td>
            </tr>
        </tbody>
    </table>


}
@section scripts
{
    @Scripts.Render("~/bundles/easyui.plus")
    <script>
        $(function () {
            $("#btnSave").click(function () {
                $("#CreateForm").validate();
                $.ajax({
                    url: "/SysSample/Create",
                    type: "Post",
                    data: $("#CreateForm").serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (data.type == 1) {
                            window.parent.frameReturnBoxByMes(data.message);
                            window.parent.frameReturnByReload(true);
                            window.parent.frameReturnByClose()
                        }
                        else {
                            window.parent.frameReturnBoxByMes(data.message);
                        }
                    }
                });

            });
        });
    </script>
}

Apps/Apps.Web/Views/SysSample/Details.cshtml
@model Apps.Models.Sys.SysSampleModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}
@section style{
    <style>
        .mvctool {
            background: #d2e0f2;
        }

            .mvctool::after {
                clear: both;
                content: '';
                display: block;
            }

        .formEditTable {
            width: 700px;
        }

            .formEditTable tr {
                border-bottom: 1px dashed;
            }

                .formEditTable tr td input {
                    margin: 2px;
                    width: 100%;
                }
    </style>
}

<table class="formEditTable setTextWidth300">
    <tbody>
        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.Name) :
            </td>
            <td style="width:310px">
                @Html.DisplayFor(model => model.Name)
            </td>

        </tr>
        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.Age) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Age)
            </td>
        </tr>
        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.Bir) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Bir)
            </td>
        </tr>
        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.Note):
            </td>
            <td>
                @Html.DisplayFor(model => model.Note)
            </td>
        </tr>

        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.CreateTime):
            </td>
            <td>
                @Html.DisplayFor(model => model.CreateTime)
            </td>
        </tr>
        <tr>
            <td style="width:100px;text-align:right;">
                @Html.LabelFor(model => model.Photo) :
            </td>
            <td>
                @Html.DisplayFor(model => model.Photo)
            </td>
        </tr>
    </tbody>
</table>

Apps/Apps.Web/Views/SysSample/Edit.cshtml
@model Apps.Models.Sys.SysSampleModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@section style{
    <style>
        .mvctool {
            background: #d2e0f2;
        }

            .mvctool::after {
                clear: both;
                content: '';
                display: block;
            }

        .formEditTable {
            width: 700px;
        }

            .formEditTable tr {
                border-bottom: 1px dashed;
            }

                .formEditTable tr td input {
                    margin: 2px;
                    width: 100%;
                }
    </style>
}
<div class="mvctool bgb">
    <a id="btnSave" style="float:left" class="l-btn l-btn-plain">
        <span class="l-btn-left">
            <span class="l-btn-text icon-save" style="padding-left:20px;">保存</span>
        </span>
    </a>
</div>

@using (Html.BeginForm("Edit", "SysSample", FormMethod.Post, new { Id = "CreateForm" }))
{
    @Html.AntiForgeryToken()

    <table class="formEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Name) :
                    @Html.HiddenFor(model => model.ID)
                </td>
                <td style="width:310px">
                    @Html.EditorFor(model => model.Name)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Age) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Age)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Age)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Bir) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Bir)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Bir)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Note):
                </td>
                <td>
                    @Html.EditorFor(model => model.Note)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Note)
                </td>
            </tr>

            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.CreateTime):
                </td>
                <td>
                    @Html.EditorFor(model => model.CreateTime)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.CreateTime)
                </td>
            </tr>
            <tr>
                <td style="width:100px;text-align:right;">
                    @Html.LabelFor(model => model.Photo) :
                </td>
                <td>
                    @Html.EditorFor(model => model.Photo)
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.Photo)
                </td>
            </tr>
        </tbody>
    </table>


}
@section scripts
{
    <script>
        $(function () {
            $("#btnSave").click(function () {
                $("#CreateForm").validate();
                $.ajax({
                    url: "/SysSample/Edit",
                    type: "Post",
                    data: $("#CreateForm").serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (data.type == 1) {
                            window.parent.frameReturnBoxByMes(data.message);
                            window.parent.frameReturnByReload(true);
                            window.parent.frameReturnByClose()
                        }
                        else {
                            window.parent.frameReturnBoxByMes(data.message);
                        }
                    }
                });

            });
        });
    </script>
}

Apps/Apps.Web/Views/SysSample/Index.cshtml
@using Apps.Common
@using Apps.Admin

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section style{
    <style type="text/css">
        .mvctool {
            margin-bottom: 5px;
        }

            .mvctool .l-btn-text {
                background-position: 5%;
            }
    </style>
}
<div id="modalwindow" class="easyui-window" data-ng-options="modal:true,closed:true,minimizable:false,shadow:false"></div>

<div class="mvctool">
    <input id="txtQuery" type="text" class="easyui-textbox">
    @Html.ToolButton("btnQuery", "icon-search", "查询")
    @Html.ToolButton("btnCreate", "icon-add", "新增")
    @Html.ToolButton("btnEdit", "icon-edit", "编辑")
    @Html.ToolButton("btnDetails", "icon-details", "详细")
    @Html.ToolButton("btnDelete", "icon-remove", "删除")
</div>

<table id="list"></table>

@section scripts{
    @Scripts.Render("~/bundles/easyui.plus")
    <script>
        $(function () {
            $("#list").datagrid({
                url: '/SysSample/GetList',
                width: $(window).width() - 10,
                methord: 'post',
                height: $(window).height() - 35,
                fitColumns: true,
                sortName: 'ID',
                sortOrder: 'desc',
                idField: 'ID',
                striped: true, //奇偶行是否区分
                singleSelect: true,//单选模式
                rownumbers: true,//行号
                pagination: true,//启用分页
                pageNumber: 1,//初始化页数
                pageSize: 10,//初始化页面大小
                pageList: [5, 10, 15, 20, 25, 30], //初始化页面大小选择
                columns: [[
                    { field: 'ID', title: 'ID', width: 80 },
                    { field: 'Name', title: '名称', width: 120 },
                    { field: 'Age', title: '年龄', width: 80, align: 'right' },
                    { field: 'Bir', title: '生日', width: 80, align: 'right' },
                    { field: 'Photo', title: '照片', width: 200 },
                    { field: 'Note', title: '说明', width: 60, align: 'center' },
                    { field: 'CreateTime', title: '创建时间', width: 100, align: 'center' }
                ]]
            });
        });
    </script>
    <script>
        //生成唯一GUID
        function GetGuid() {
            var s4 = function () {
                return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
            };
            return s4() + s4() + s4() + "-" + s4();
        }

        //关闭iframe
        function frameReturnByClose() {
            $("#modalwindow").window('close');
        }

        function frameReturnByReload(flag) {
            if (flag)
                $("#list").datagrid('load');
            else
                $("#list").datagrid('reload');
        }

        //弹框提示
        function frameReturnByMes(mes) {
            $.messager.alert("提示", mes);
        }

        function frameReturnBoxByMes(mes) {
            $.messageBox5s('提示', mes);
        }


        $(function () {
            //关闭window弹窗
            $("#modalwindow").window('close');
            //新增
            $("#btnCreate").click(function () {
                $("#modalwindow").html("<iframe width='100%' height='80%' scrolling='no' frameborder='0' src='SysSample/Create'></iframe>")
                    .window({ title: '新增', width: 700, height: 400, iconCls: 'icon-add', modal: true })
                    .window('open')
                    .window("center");
            });
            //编辑
            $("#btnEdit").click(function () {
                var row = $("#list").datagrid("getSelected");

                if (row != null) {
                    $("#modalwindow").html("<iframe width='100%' height='80%' scrolling='no' frameborder='0' src='SysSample/Edit?ID=" + row.ID + "&Ieguid=" + GetGuid() + "'></iframe>")
                    .window({ title: '编辑', width: 700, height: 430, iconCls: 'icon-edit', modal: true })
                    .window("open")
                    .window("center");
                }
                else {
                    $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords');
                }
            });

            //详细信息
            $("#btnDetails").click(function () {
                var row = $("#list").datagrid("getSelected");
                if (row != null) {
                    $("#modalwindow").html("<iframe width='100%' height='80%' scrolling='no' frameborder='0' src='SysSample/Details?id=" + row.ID + "&Ieguid=" + GetGuid() + "'></iframe>")
                     .window({ title: '详细', width: 500, height: 300, iconCls: 'icon-details', modal: true })
                     .window("open")
                    .window("center");
                }
                else {
                    $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords');
                }
            });


            //查询
            $("#btnQuery").click(function () {
                var query = $("#txtQuery").val();
                if (query == null || query == '') {
                    query = "%";
                }
                $("#list").datagrid({
                    url: '/SysSample/GetList?queryStr=' + encodeURI(query)
                });
            });

            //删除
            $("#btnDelete").click(function () {
                var row = $("#list").datagrid("getSelected");
                if (row != null) {
                    $.messager.confirm("提示", "@Suggestion.YouWantToDeleteTheSelectedRecords", function (r) {
                        if (r) {
                            $.post("/SysSample/Delete?id=" + row.ID, function (data) {
                                if (data.type == 1) {
                                    $("#list").datagrid('reload');
                                    $.messageBox5s('提示', data.message);
                                    return;
                                }
                                $.messageBox5s('提示', data.message);
                            });
                        }
                    }, "json");
                }
                else {
                    $.messageBox5s('提示', '@Suggestion.PlaseChooseToOperatingRecords');
                }
            });
        });
    </script>
}